language: r
cache: packages

install:
  - Rscript -e 'if (!requireNamespace("BiocManager", quietly=TRUE))  install.packages("BiocManager", lib = "/home/travis/R/Library");if (FALSE) BiocManager::install(version = "devel", ask = FALSE);cat(append = TRUE, file = "~/.Rprofile.site", "options(repos = BiocManager::repositories());")'

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
