language: r
cache: packages

before_install:
  - chmod +x ./travis-config.sh && ./travis-config.sh

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
